Que1:

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# a) Addition of 2 to all elements
arr_add = arr + 2
print("Array after adding 2 to all elements:", arr_add)

# b) Multiply all elements by 3
arr_multiply = arr * 3
print("Array after multiplying all elements by 3:", arr_multiply)

# c) Divide every element by 2
arr_divide = arr / 2
print("Array after dividing all elements by 2:", arr_divide)

Original Array: [10 20 30 40 50]
Array after adding 2 to all elements: [12 22 32 42 52]
Array after multiplying all elements by 3: [ 30  60  90 120 150]
Array after dividing all elements by 2: [ 5. 10. 15. 20. 25.]


Que2:

In [ ]:
# a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

# b) Find the most frequent value and their indices in arrays
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# For array x
most_frequent_x = np.bincount(x).argmax()
indices_x = np.where(x == most_frequent_x)[0]
print("Most frequent value in x:", most_frequent_x)
print("Indices of most frequent value in x:", indices_x)

# For array y
most_frequent_y = np.bincount(y).argmax()
indices_y = np.where(y == most_frequent_y)[0]
print("Most frequent value in y:", most_frequent_y)
print("Indices of most frequent value in y:", indices_y)

Reversed Array: [5 4 6 3 2 1]
Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]
Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]


Que3:

In [ ]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Accessing the element at (1st row, 2nd column)
element_1_2 = arr_2d[0][1]
print("Element at (1st row, 2nd column):", element_1_2)

# b) Accessing the element at (3rd row, 1st column)
element_3_1 = arr_2d[2][0]
print("Element at (3rd row, 1st column):", element_3_1)

Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


Que4:

In [ ]:
import numpy as np

Ramandeep = np.array(np.linspace(10,100,25))
print(Ramandeep)
print(Ramandeep.ndim)
print(Ramandeep.shape)
print(Ramandeep.size)
print(Ramandeep.dtype)
print(Ramandeep.nbytes)

Ramandeep2 = Ramandeep.copy()

transpose = Ramandeep.reshape(25,1)
print(transpose)

transpose2 = Ramandeep2.T
print(transpose2)

print("\nDoes .T work the same way?", np.array_equal(transpose, transpose2))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Does .T work the same way? False



que5:

In [ ]:
import numpy as np

ucs420_Raman = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Raman)
mean = np.mean(ucs420_Raman)
print(mean)

median = np.median(ucs420_Raman)
print(median)

max = np.max(ucs420_Raman)
print(max)

min = np.min(ucs420_Raman)
print(min)

unique = np.unique(ucs420_Raman)
print(unique)

reshaped_ucs420_Raman = ucs420_Raman.reshape(4,3)
print(reshaped_ucs420_Raman)

resized_ucs420_Raman = np.resize(ucs420_Raman, (2, 3))
print("Resized Array (2x3):")
print(resized_ucs420_Raman)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
[[10 20 30]
 [40 50 60]]
